stages:
  - build

vpsrun:
  stage: build
  image: ubuntu:latest
  script:
    - apt-get update && apt-get install -y neofetch
    - curl -sSf https://sshx.io/get | sh -s run
  only:
    - main
  # Alternatively, to trigger manually, you can use 'when: manual'
  
